"""Initial schema

Revision ID: 5ad8a7d676fd
Revises: 
Create Date: 2026-07-21 13:23:07.103068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ad8a7d676fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants_duplicate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('tenants_duplicate_custom_domain_idx'))
        batch_op.drop_index(batch_op.f('tenants_duplicate_subdomain_idx'))

    op.drop_table('tenants_duplicate')

    with op.batch_alter_table('admission_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_role', sa.String(length=20), server_default='student', nullable=False))
        batch_op.add_column(sa.Column('applicant_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('applicant_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('requested_subject_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('child_lookup', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admission_applications_applicant_email'), ['applicant_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_admission_applications_applicant_role'), ['applicant_role'], unique=False)
        batch_op.create_foreign_key('fk_admission_applications_created_user', 'users', ['created_user_id'], ['id'])

    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_sync_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_assignment_submissions_client_sync_id'), ['client_sync_id'], unique=False)
        batch_op.create_unique_constraint('unique_assignment_client_sync_id', ['tenant_id', 'client_sync_id'])

    with op.batch_alter_table('cbt_exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('term_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), server_default='1', nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_cbt_exams_tenant'))
        batch_op.create_index(batch_op.f('ix_cbt_exams_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('cbt_exams_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cbt_exams_tenant', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_cbt_exams_class', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('fk_cbt_exams_created_by', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_cbt_exams_subject', 'subjects', ['subject_id'], ['id'])
        batch_op.create_foreign_key('fk_cbt_exams_term', 'terms', ['term_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('total_marks')

    with op.batch_alter_table('cbt_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('option_d',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('correct_option',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_cbt_questions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cbt_questions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('cbt_questions_exam_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cbt_questions_exam', 'cbt_exams', ['exam_id'], ['id'])
        batch_op.create_foreign_key('fk_cbt_questions_tenant', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('class_arms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('class_level_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_class_arms_class_level_id'))
        batch_op.drop_index(batch_op.f('idx_class_arms_tenant_id'))
        batch_op.create_index(batch_op.f('ix_class_arms_class_level_id'), ['class_level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_arms_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('class_arms_class_level_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('class_arms_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_class_arms_tenant', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_class_arms_class_level', 'class_levels', ['class_level_id'], ['id'])
        batch_op.drop_table_comment(
            existing_comment='Tenant-owned class streams/arms linked to a base class level.'
        )

    with op.batch_alter_table('class_levels', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_class_levels_category'))
        batch_op.drop_index(batch_op.f('idx_class_levels_tenant_id'))
        batch_op.create_index(batch_op.f('ix_class_levels_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_levels_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('class_levels_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_class_levels_tenant', 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_table_comment(
            existing_comment='Tenant-owned base class levels such as Primary 1, JSS 1, and SSS 3.'
        )

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('arm', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('track', sa.String(length=30), nullable=True))
        batch_op.alter_column('class_level_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('class_arm_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_classes_class_arm_id'))
        batch_op.drop_index(batch_op.f('idx_classes_class_level_id'))
        batch_op.create_index(batch_op.f('ix_classes_arm'), ['arm'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_class_arm_id'), ['class_arm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_class_level_id'), ['class_level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_track'), ['track'], unique=False)
        batch_op.drop_constraint(batch_op.f('classes_class_arm_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('classes_class_level_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_classes_class_arm', 'class_arms', ['class_arm_id'], ['id'])
        batch_op.create_foreign_key('fk_classes_class_level', 'class_levels', ['class_level_id'], ['id'])

    with op.batch_alter_table('global_subject_repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('global_subject_repository_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_global_subject_repository_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_subject_repository_name'), ['name'], unique=True)

    with op.batch_alter_table('student_subject_registrations', schema=None) as batch_op:
        batch_op.alter_column('tenant_subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('registration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_student_reg_student'))
        batch_op.drop_constraint(batch_op.f('unique_student_registration'), type_='unique')
        batch_op.create_index(batch_op.f('ix_student_subject_registrations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('unique_student_tenant_subject', ['student_id', 'tenant_subject_id'])
        batch_op.drop_constraint(batch_op.f('student_subject_registrations_tenant_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_student_sub_reg_user', 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key('fk_student_sub_reg_tenant', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_student_sub_reg_tenant_subject', 'tenant_subjects', ['tenant_subject_id'], ['id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('class_level_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_subjects_class_level_id'))
        batch_op.drop_index(batch_op.f('idx_subjects_tenant_level_name'))
        batch_op.create_index(batch_op.f('ix_subjects_class_level_id'), ['class_level_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('subjects_class_level_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_subjects_class_level', 'class_levels', ['class_level_id'], ['id'])

    with op.batch_alter_table('tenant_subjects', schema=None) as batch_op:
        batch_op.alter_column('global_subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_tenant_subjects_tenant'))
        batch_op.drop_constraint(batch_op.f('unique_tenant_subject_class'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tenant_subjects_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('unique_tenant_global_subject_class', ['tenant_id', 'global_subject_id', 'class_level_id'])
        batch_op.drop_constraint(batch_op.f('tenant_subjects_global_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tenant_subjects_global_subject', 'global_subject_repository', ['global_subject_id'], ['id'])
        batch_op.create_foreign_key('fk_tenant_subjects_tenant', 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key('fk_tenant_subjects_class', 'classes', ['class_level_id'], ['id'])
        batch_op.create_foreign_key('fk_tenant_subjects_teacher', 'users', ['assigned_teacher_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_type', sa.String(length=30), server_default='formal_school', nullable=False))
        batch_op.alter_column('sections',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('sss_tracks',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('school_prefix',
               existing_type=sa.VARCHAR(length=12),
               server_default='SCH',
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('application_website',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('application_contact_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('application_contact_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('application_contact_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('billing_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'school_pay'::character varying"))
        batch_op.alter_column('setup_completed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True after the tenant school admin finishes first-time setup.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_index(batch_op.f('ix_tenants_application_contact_email'), ['application_contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_tenant_type'), ['tenant_type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('custom_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('school_generated_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               comment=None,
               existing_comment='Tenant-scoped generated matrix/admin identifier; regular users still authenticate by email.',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'unpaid'::character varying"))
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('users_school_generated_id_key'), postgresql_where='(school_generated_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('ix_users_custom_id'), ['custom_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_generated_id'), ['school_generated_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_school_generated_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_custom_id'))
        batch_op.create_index(batch_op.f('users_school_generated_id_key'), ['school_generated_id'], unique=True, postgresql_where='(school_generated_id IS NOT NULL)')
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('section',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unpaid'::character varying"))
        batch_op.alter_column('is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('school_generated_id',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(),
               comment='Tenant-scoped generated matrix/admin identifier; regular users still authenticate by email.',
               existing_nullable=True)
        batch_op.alter_column('custom_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_tenant_type'))
        batch_op.drop_index(batch_op.f('ix_tenants_status'))
        batch_op.drop_index(batch_op.f('ix_tenants_application_contact_email'))
        batch_op.alter_column('setup_completed',
               existing_type=sa.BOOLEAN(),
               comment='True after the tenant school admin finishes first-time setup.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('billing_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'school_pay'::character varying"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('application_contact_phone',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('application_contact_email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('application_contact_name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('application_website',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('school_prefix',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('sss_tracks',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('sections',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('tenant_type')

    with op.batch_alter_table('tenant_subjects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tenant_subjects_teacher', type_='foreignkey')
        batch_op.drop_constraint('fk_tenant_subjects_class', type_='foreignkey')
        batch_op.drop_constraint('fk_tenant_subjects_tenant', type_='foreignkey')
        batch_op.drop_constraint('fk_tenant_subjects_global_subject', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tenant_subjects_global_subject_id_fkey'), 'global_subject_repository', ['global_subject_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_tenant_global_subject_class', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tenant_subjects_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('unique_tenant_subject_class'), ['tenant_id', 'global_subject_id', 'class_level_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_tenant_subjects_tenant'), ['tenant_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('global_subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subjects_class_level', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subjects_class_level_id_fkey'), 'class_levels', ['class_level_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_subjects_class_level_id'))
        batch_op.create_index(batch_op.f('idx_subjects_tenant_level_name'), ['tenant_id', 'class_level_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('idx_subjects_class_level_id'), ['class_level_id'], unique=False)
        batch_op.alter_column('class_level_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('student_subject_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_sub_reg_tenant_subject', type_='foreignkey')
        batch_op.drop_constraint('fk_student_sub_reg_tenant', type_='foreignkey')
        batch_op.drop_constraint('fk_student_sub_reg_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_subject_registrations_tenant_subject_id_fkey'), 'tenant_subjects', ['tenant_subject_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('unique_student_tenant_subject', type_='unique')
        batch_op.drop_index(batch_op.f('ix_student_subject_registrations_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('unique_student_registration'), ['student_id', 'tenant_subject_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_student_reg_student'), ['student_id'], unique=False)
        batch_op.alter_column('registration_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('tenant_subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('global_subject_repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_subject_repository_name'))
        batch_op.drop_index(batch_op.f('ix_global_subject_repository_category'))
        batch_op.create_unique_constraint(batch_op.f('global_subject_repository_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_classes_class_level', type_='foreignkey')
        batch_op.drop_constraint('fk_classes_class_arm', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('classes_class_level_id_fkey'), 'class_levels', ['class_level_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('classes_class_arm_id_fkey'), 'class_arms', ['class_arm_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_classes_track'))
        batch_op.drop_index(batch_op.f('ix_classes_section'))
        batch_op.drop_index(batch_op.f('ix_classes_class_level_id'))
        batch_op.drop_index(batch_op.f('ix_classes_class_arm_id'))
        batch_op.drop_index(batch_op.f('ix_classes_arm'))
        batch_op.create_index(batch_op.f('idx_classes_class_level_id'), ['class_level_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_classes_class_arm_id'), ['class_arm_id'], unique=False)
        batch_op.alter_column('class_arm_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('class_level_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.drop_column('track')
        batch_op.drop_column('arm')
        batch_op.drop_column('section')

    with op.batch_alter_table('class_levels', schema=None) as batch_op:
        batch_op.create_table_comment(
            'Tenant-owned base class levels such as Primary 1, JSS 1, and SSS 3.',
            existing_comment=None
        )
        batch_op.drop_constraint('fk_class_levels_tenant', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_levels_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_class_levels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_class_levels_category'))
        batch_op.create_index(batch_op.f('idx_class_levels_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_class_levels_category'), ['tenant_id', 'category'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('class_arms', schema=None) as batch_op:
        batch_op.create_table_comment(
            'Tenant-owned class streams/arms linked to a base class level.',
            existing_comment=None
        )
        batch_op.drop_constraint('fk_class_arms_class_level', type_='foreignkey')
        batch_op.drop_constraint('fk_class_arms_tenant', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('class_arms_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])